#!/usr/bin/env bash

VERSION="2.77"
URL="http://www.bulletphysics.com/"
ARCHIVE_FILENAME="bullet-${VERSION}.tgz"
DOWNLOAD_URL="http://bullet.googlecode.com/files/${ARCHIVE_FILENAME}"
DEPEND=""

# TODO: install the vectormath library separately, and use
# -DUSE_SYSTEM_VECTORMATH

function custom_build() {
	rm -rf build 2>/dev/null
	mkdir build && \
	cd build && \
	ios_msg "${text_bold}Compiling source code…" && \
	find ../src/{LinearMath,BulletCollision,BulletDynamics} -iname "*.cpp" -print0 | \
		xargs -0 -t -P $MAXJOBS -I % \
		"${CXX}" -c ${CXXFLAGS} -DNDEBUG -I../src % && \
	ios_msg "${text_bold}Creating static library…" && \
	"${AR}" -rv "${PREFIX}/lib/libbullet.a" *.o && \
	ios_sign_library "${PREFIX}/lib/libbullet.a" && \
	ios_msg "${text_bold}Installing header files…" && \
	cd ../src && \
	find {.,LinearMath,BulletCollision,BulletDynamics} -iname "*.h" -print0 | cpio -0 -pdmuv "${PREFIX}/include/bullet"
}

. "$(dirname "$0")/../../scripts/builder"

