#!/usr/bin/env/bash

VERSION="1.2.5"
URL="http://www.zlib.net/"
ARCHIVE_FILENAME="zlib-${VERSION}.tar.gz"
DOWNLOAD_URL="http://sourceforge.net/projects/libpng/files/${ARCHIVE_FILENAME}/download"

function custom_build() {
	cd contrib/minizip && \
	"$CC" -c $CFLAGS -I. -DSTDC -DNOUNCRYPT -DNOCRYPT -DNO_ADDFILEINEXISTINGZIP unzip.c zip.c ioapi.c mztools.c && \
	"$AR" -r "$PREFIX/lib/libminizip.a" unzip.o zip.o ioapi.o mztools.o && \
	mkdir -p "$PREFIX/include/minizip" && \
	cp unzip.h zip.h ioapi.h mztools.h "$PREFIX/include/minizip/" && \
	rm *.o
}

. "$(dirname "$0")/../../scripts/builder"

