#!/bin/bash

VERSION="1.4.5"
URL="http://www.libpng.org/"
ARCHIVE_FILENAME="libpng-${VERSION}.tar.gz"
DOWNLOAD_URL="http://prdownloads.sourceforge.net/libpng/${ARCHIVE_FILENAME}?download"

function custom_build() {
	$XCONF \
	&& make -j $MAXJOBS \
	&& for LIB in .libs/*.a
	do
		ios_sign_library "$LIB"
	done \
	&& make -j $MAXJOBS install \
	&& make -j $MAXJOBS distclean
}

. "$(dirname "$0")/../../scripts/builder"

