#!/bin/bash

VERSION="1.45.0"
URL="http://www.boost.org/"
ARCHIVE_FILENAME="boost_${VERSION//./_}.tar.bz2"
DOWNLOAD_URL="http://sourceforge.net/projects/boost/files/boost/${VERSION}/${ARCHIVE_FILENAME}/download"

function custom_build() {
	./bootstrap.sh --without-libraries=python,graph,graph_parallel,mpi,wave,program_options && \
	./bjam --prefix="${IOS_DEVICE_PREFIX}" toolset=darwin-4.2.1~iphone architecture=arm target-os=iphone macosx-version=iphone-${SDK} link=static threading=multi --layout=versioned --variant=release,debug install && \
	./bootstrap.sh --without-libraries=python,graph,graph_parallel,mpi,wave,program_options && \
	./bjam --prefix="${IOS_SIMULATOR_PREFIX}" toolset=darwin-4.2.1~iphonesim architecture=x86 target-os=iphone macosx-version=iphone-${SDK} link=static threading=multi --layout=versioned --variant=release,debug install
}

. "${IOS_OVERLAY_PATH}/scripts/builder"

