#!/usr/bin/env bash

VERSION="1.45.0"
URL="http://www.boost.org/"
ARCHIVE_FILENAME="boost_${VERSION//./_}.tar.bz2"
DOWNLOAD_URL="http://sourceforge.net/projects/boost/files/boost/${VERSION}/${ARCHIVE_FILENAME}/download"
DEPEND="bzip2"

function write_jamfile() {
	cat >"${IOS_BUILD_DIR}/ios.jam" <<EOT
using darwin : iphone
	: ${CC}
	: <striper>
	: <architecture>arm <target-os>iphone
;

using darwin : iphonesim
	: ${CC}
	: <striper>
	: <architecture>x86 <target-os>iphone
;
EOT
}

function custom_build() {
	if [ "$SDK" == "iphoneos" ]
	then
		local x_toolset=iphone
		local x_arch=arm
		local x_defs="-D_LITTLE_ENDIAN"
	else
		local x_toolset=iphonesim
		local x_arch=x86
	fi

	if [ ! -r "${IOS_BUILD_DIR}/ios.jam" ]
	then
		./bootstrap.sh && write_jamfile
	fi && \
	./bjam \
		-j $MAXJOBS \
		--user-config="${IOS_BUILD_DIR}/ios.jam" \
		--prefix="${PREFIX}" \
		toolset=darwin-$x_toolset \
		architecture=$x_arch \
		target-os=iphone \
		macosx-version=iphone-${SDKVER} \
		link=static \
		threading=multi \
		cflags="${CFLAGS} -fvisibility=hidden -fvisibility-inlines-hidden $x_defs" \
		cxxflags="${CFLAGS} -fvisibility=hidden -fvisibility-inlines-hidden $x_defs" \
		linkflags="${LDFLAGS}" \
		--layout=system \
		--variant=release \
		--without-python \
		--without-graph \
		--without-graph_parallel \
		--without-mpi \
		--without-wave \
		--without-program_options \
		install && \
	find "${PREFIX}/lib" -iname "boost_*.a" -print0 >.librairies_to_sign && \
	while IFS= read -r -d $'\0' LIB
	do
		ios_sign_library "$LIB"
	done <.librairies_to_sign
}

. "$(dirname "$0")/../../scripts/builder"

