#!/bin/bash

VERSION="1.45.0"
URL="http://www.boost.org/"
ARCHIVE_FILENAME="boost_${VERSION//./_}.tar.bz2"
DOWNLOAD_URL="http://sourceforge.net/projects/boost/files/boost/${VERSION}/${ARCHIVE_FILENAME}/download"
DEPEND="bzip2"

function write_jamfile() {
	cat >"${IOS_BUILD_DIR}/ios.jam" <<EOT
using darwin : iphone
	: ${IOS_DEVICE_CC}
	:
	<striper>
	<compileflags>"${IOS_DEVICE_PERFORMANCE_CFLAGS} -fvisibility=hidden -fvisibility-inlines-hidden -D_LITTLE_ENDIAN"
	<linkflags>"${IOS_DEVICE_LDFLAGS}"
	: <architecture>arm <target-os>iphone
;

using darwin : iphonesim
	: ${IOS_SIMULATOR_CC}
	: <striper>
	<compileflags>"${IOS_SIMULATOR_CFLAGS} -fvisibility=hidden -fvisibility-inlines-hidden"
	<linkflags>"${IOS_SIMULATOR_LDFLAGS}"
	: <architecture>x86 <target-os>iphone
;
EOT
}

function custom_build() {
	write_jamfile
	./bootstrap.sh && \
	./bjam \
		--user-config="${IOS_BUILD_DIR}/ios.jam" \
		--prefix="${IOS_DEVICE_PREFIX}" \
		toolset=darwin-iphone \
		architecture=arm \
		target-os=iphone \
		macosx-version=iphone-${IOS_SDK} \
		link=static \
		threading=multi \
		--layout=system \
		--variant=release \
		--without-python \
		--without-graph \
		--without-graph_parallel \
		--without-mpi \
		--without-wave \
		--without-program_options \
		install && \
	./bjam \
		--user-config="${IOS_BUILD_DIR}/ios.jam" \
		--prefix="${IOS_SIMULATOR_PREFIX}" \
		toolset=darwin-iphonesim \
		architecture=x86 \
		target-os=iphone \
		macosx-version=iphone-${IOS_SDK} \
		link=static \
		threading=multi \
		--layout=system \
		--variant=release \
		--without-python \
		--without-graph \
		--without-graph_parallel \
		--without-mpi \
		--without-wave \
		--without-program_options \
		install
}

. "$(dirname "$0")/../../scripts/builder"

