#!/bin/bash

VERSION="trunk"
URL="http://code.google.com/p/opencollada/"
DOWNLOAD_URL="svn|http://opencollada.googlecode.com/svn/trunk/"

function color_message() {
	echo -e "[32;1m[${@}][0m"
}

function custom_build() {
	echo "*** Not ready"
	false
}

. "$(dirname "$0")/../../scripts/builder"

