#!/bin/bash

VERSION="8.10"
URL="http://www.pcre.org/"
ARCHIVE_FILENAME="pcre-${VERSION}.tar.bz2"
DOWNLOAD_URL="http://sourceforge.net/projects/pcre/files/pcre/${VERSION}/${ARCHIVE_FILENAME}/download"

function custom_build() {
	if [ "$TARGET" == "device" ]
	then
		local x_flags="--host=arm-apple-darwin"
	fi
	CXX="$CXX" LD="$LD" CC="$CC" CPP="$CPP" AR="$AR" \
	./configure \
		--prefix="$PREFIX" \
		--disable-shared \
		--enable-utf8 \
		$x_flags \
		CFLAGS="$CFLAGS" \
		CXXFLAGS="$CFLAGS" \
		LDFLAGS="$LDFLAGS" \
	&& make -j $MAXJOBS \
	&& for LIB in .libs/*.a
	do
		ios_sign_library "$LIB"
	done \
	&& make -j $MAXJOBS install \
	&& make -j $MAXJOBS distclean
}

. "$(dirname "$0")/../../scripts/builder"

