#!/usr/bin/env bash

VERSION="8.10"
URL="http://www.pcre.org/"
ARCHIVE_FILENAME="pcre-${VERSION}.tar.bz2"
DOWNLOAD_URL="http://sourceforge.net/projects/pcre/files/pcre/${VERSION}/${ARCHIVE_FILENAME}/download"

function custom_build() {
	$XCONF --enable-utf8 \
	&& make -j $MAXJOBS \
	&& for LIB in .libs/*.a
	do
		ios_sign_library "$LIB"
	done \
	&& make -j $MAXJOBS install \
	&& make -j $MAXJOBS distclean
}

. "$(dirname "$0")/../../scripts/builder"

