#!/usr/bin/env bash

VERSION="6b"
URL="http://www.ijg.org/"
ARCHIVE_FILENAME="jpegsrc.v${VERSION}.tar.gz"
DOWNLOAD_URL="http://distfiles.macports.org/jpeg/${ARCHIVE_FILENAME}"

function write_config() {
	cat >jconfig.h <<-EOT
		#define HAVE_PROTOTYPES
		#define HAVE_UNSIGNED_CHAR
		#define HAVE_UNSIGNED_SHORT
		#ifndef HAVE_STDDEF_H
			#define HAVE_STDDEF_H
		#endif
		#ifndef HAVE_STDLIB_H
			#define HAVE_STDLIB_H
		#endif
		#undef NEED_BSD_STRINGS
		#undef NEED_SYS_TYPES_H
		#undef NEED_FAR_POINTERS
		#undef NEED_SHORT_EXTERNAL_NAMES
		#undef CHAR_IS_UNSIGNED
		#ifdef JPEG_INTERNALS
			#undef RIGHT_SHIFT_IS_UNSIGNED
			#ifdef XP_MAC
				#define ALIGN_TYPE long
				#define NO_GETENV
			#endif
		#endif
	EOT
}

function custom_build() {
	write_config && \
	make -f makefile.unix -j $MAXJOBS ansi2knr && \
	make -f makefile.unix -j $MAXJOBS libjpeg.a \
		CC="${CC}" \
		AR="${AR} -r" \
		AR2="touch" \
		CFLAGS="${CFLAGS}" \
	&& \
	mv libjpeg.a "${PREFIX}/lib/" && \
	cp jconfig.h jerror.h jmorecfg.h jpeglib.h "${PREFIX}/include/" && \
	make -f makefile.unix clean
}

. "$(dirname "$0")/../../scripts/builder"

