#!/bin/bash

VERSION="6b"
URL="http://www.ijg.org/"
ARCHIVE_FILENAME="jpegsrc.v${VERSION}.tar.gz"
DOWNLOAD_URL="http://distfiles.macports.org/jpeg/${ARCHIVE_FILENAME}"

function custom_build() {
	for HACK in 1
	do
		cat >jconfig.h <<-EOT
			#define HAVE_PROTOTYPES 
			#define HAVE_UNSIGNED_CHAR 
			#define HAVE_UNSIGNED_SHORT 
			#ifndef HAVE_STDDEF_H 
				#define HAVE_STDDEF_H 
			#endif
			#ifndef HAVE_STDLIB_H
				#define HAVE_STDLIB_H 
			#endif
			#undef NEED_BSD_STRINGS
			#undef NEED_SYS_TYPES_H
			#undef NEED_FAR_POINTERS
			#undef NEED_SHORT_EXTERNAL_NAMES
			#undef CHAR_IS_UNSIGNED
			#ifdef JPEG_INTERNALS
				#undef RIGHT_SHIFT_IS_UNSIGNED
				#ifdef XP_MAC
					#define ALIGN_TYPE long
					#define NO_GETENV
				#endif
			#endif
		EOT
	done && \
	make -f makefile.unix ansi2knr && \
	make -f makefile.unix libjpeg.a \
		CC="${IOS_DEVICE_CC}" \
		AR="${IOS_DEVICE_AR} -r" \
		AR2="touch" \
		CFLAGS="${IOS_DEVICE_PERFORMANCE_CFLAGS}" \
	&& \
	mv libjpeg.a "${IOS_DEVICE_PREFIX}/lib/" && \
	cp jconfig.h jerror.h jmorecfg.h jpeglib.h "${IOS_DEVICE_PREFIX}/include/" && \
	make -f makefile.unix clean && \
	make -f makefile.unix ansi2knr && \
	make -f makefile.unix libjpeg.a \
		CC="${IOS_SIMULATOR_CC}" \
		AR="${IOS_SIMULATOR_AR} -r" \
		AR2="touch" \
		CFLAGS="${IOS_SIMULATOR_CFLAGS}" \
	&& \
	mv libjpeg.a "${IOS_SIMULATOR_PREFIX}/lib/" && \
	cp jconfig.h jerror.h jmorecfg.h jpeglib.h "${IOS_SIMULATOR_PREFIX}/include/" && \
	make -f makefile.unix clean
}

. "$(dirname "$0")/../../scripts/builder"

