#!/bin/bash

VERSION="1.0.6"
URL="http://bzip.org/"
ARCHIVE_FILENAME="bzip2-${VERSION}.tar.gz"
DOWNLOAD_URL="http://bzip.org/${VERSION}/bzip2-${VERSION}.tar.gz"
ARCHIVE_MD5="00b516f4704d4a7cb50a1d97e6e8e15b"

function custom_build() {
	make libbz2.a \
		-j $MAXJOBS \
		PREFIX="${PREFIX}" \
		CC="${CC}" \
		AR="${AR}" \
		RANLIB="${RANLIB}" \
		CFLAGS="${CFLAGS} -D_FILE_OFFSET_BITS=64" \
		LDFLAGS="${LDFLAGS}" && \
	mv "${IOS_BUILD_DIR}/libbz2.a" "${PREFIX}/lib/" && \
	make clean && \
	cp "${IOS_BUILD_DIR}/bzlib.h" "${PREFIX}/include/"
}

. "$(dirname "$0")/../../scripts/builder"

