#!/bin/bash

VERSION="1.0.0"
URL="http://ebml.sourceforge.net/"
ARCHIVE_FILENAME="libebml-${VERSION}.tar.bz2"
DOWNLOAD_URL="http://dl.matroska.org/downloads/libebml/${ARCHIVE_FILENAME}"
LICENSE="LGPL"

function custom_build() {
	cd make/linux && \
	make -j $MAXJOBS \
		CROSS="${PLATFORM}/usr/bin/" \
		CPPFLAGS="${CFLAGS}" \
		prefix="${PREFIX}" && \
	ios_sign_library libebml.a && \
	make -j $MAXJOBS \
		CROSS="${PLATFORM}/usr/bin/" \
		CPPFLAGS="${CFLAGS}" \
		prefix="${PREFIX}" install clean
}

. "$(dirname "$0")/../../scripts/builder"

