#!/bin/bash

function ios_create_master_link() {
	sudo rm -rf "/iOS_SDK_Overlay" 2>/dev/null
	sudo ln -sf "${MY_DIR}" "/iOS_SDK_Overlay"
}

# Get the canonical path for our install
MY_DIR=${0%/*}
MY_DIR=${MY_DIR:-.}
cd "${MY_DIR}/.."
MY_DIR=$(pwd)
cd $OLDPWD

if [ "$MY_DIR" != "$(readlink /iOS_SDK_Overlay)" ]; then ios_create_master_link; exit 0; fi
if [ "$MY_DIR" != "$(readlink /iOS_SDK_Overlay)" ]; then exit 1; fi

