#!/usr/bin/env bash

VERSION="3.05B"
URL="http://sourceforge.net/projects/colladamaya/files/COLLADAMaya%201.4.1%20plug-ins/${VERSION}/"
ARCHIVE_FILENAME="FCollada_FREE_${VERSION}.zip"
DOWNLOAD_URL="${URL}${ARCHIVE_FILENAME}/download"
#DEPEND="bzip2 boost pcre"

function custom_build() {
	rm *.o 2>/dev/null
	find {FCollada,FCollada/FCDocument,FCollada/FMath,FCollada/FUtils,FColladaPlugins/FArchiveXML} \
	-maxdepth 1 -iname "*.cpp" -print0 | \
	xargs -0 -t -P 4 -I % \
		"${CXX}" -c ${CFLAGS} \
			-DLINUX -DNDEBUG -DRETAIL -DUNICODE \
			-I/usr/include/libxml2 -I. -IFCollada % && \
	"${AR}" -r "${PREFIX}/lib/libfcollada.a" *.o && \
	ios_sign_library "${PREFIX}/lib/libfcollada.a" && \
	for DIR in FCollada FCollada/FCDocument FCollada/FMath FCollada/FUtils FColladaPlugins/FArchiveXML
	do
		mkdir -p "${PREFIX}/include/$DIR" && cp -v "${DIR}"/*.h "${PREFIX}/include/${DIR}/"
	done
}

. "$(dirname "$0")/../../scripts/builder"

